version: '3.8'

services:
  recaptcha-authz:
    build: .
    ports:
      - "8000:8000"  # HTTP port
      - "9000:9000"  # gRPC port
    environment:
      - RECAPTCHA_PROJECT_ID=rj-superapp-staging
      - RECAPTCHA_SITE_KEY=YOUR_RECAPTCHA_SITE_KEY
      - RECAPTCHA_ACTION=authz
      - RECAPTCHA_V3_THRESHOLD=0.5
      - GOOGLE_API_TIMEOUT_SECONDS=5
      - CACHE_TTL_SECONDS=30
      - CACHE_FAILED_TTL_SECONDS=300
      - REDIS_URL=redis://redis:6379
      - FAILURE_MODE=fail_open
      - CIRCUIT_BREAKER_ENABLED=true
      - CIRCUIT_BREAKER_FAILURE_THRESHOLD=5
      - CIRCUIT_BREAKER_RECOVERY_TIME_SECONDS=60
      - HEALTH_CHECK_INTERVAL_SECONDS=30
      - OTEL_ENDPOINT=http://signoz-collector:4317
      - OTEL_SERVICE_NAME=recaptcha-authz
      - LOG_LEVEL=debug
      - MOCK_MODE=true
    depends_on:
      - redis
    command: ["./recaptcha-authz", "--http=8000", "--grpc=9000"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Optional: SignOz for observability
  signoz-collector:
    image: signoz/signoz-otel-collector:latest
    ports:
      - "4317:4317"
    environment:
      - SIGNOZ_API_URL=http://signoz-query-service:8080
    depends_on:
      - signoz-query-service

  signoz-query-service:
    image: signoz/query-service:latest
    ports:
      - "8080:8080"
    environment:
      - STORAGE_BACKEND=sqlite
      - SQLITE_STORAGE_PATH=/var/lib/signoz/signoz.db

volumes:
  redis_data: 