---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recaptcha-authz
  labels:
    app: recaptcha-authz
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recaptcha-authz
  template:
    metadata:
      labels:
        app: recaptcha-authz
    spec:
      containers:
      - name: recaptcha-authz
        image: ghcr.io/prefeitura-rio/app-ext-authz:latest
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 9000
          name: grpc
          protocol: TCP
        envFrom:
        - secretRef:
            name: recaptcha-authz-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "1000m"
          limits:
            memory: "512Mi"
            cpu: "2000m"
        # Note: No health probes since this is an Envoy ext_authz service
        # The service is considered healthy if it responds to authorization requests
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: recaptcha-authz
  labels:
    app: recaptcha-authz
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: grpc
  selector:
    app: recaptcha-authz

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recaptcha-authz-hpa
  labels:
    app: recaptcha-authz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recaptcha-authz
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recaptcha-authz-pdb
  labels:
    app: recaptcha-authz
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: recaptcha-authz
