---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recaptcha-authz
  labels:
    app: recaptcha-authz
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recaptcha-authz
  template:
    metadata:
      labels:
        app: recaptcha-authz
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: recaptcha-authz
        image: ghcr.io/prefeitura-rio/app-ext-authz:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: recaptcha-authz-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "1000m"
          limits:
            memory: "512Mi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: recaptcha-authz
  labels:
    app: recaptcha-authz
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: recaptcha-authz

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recaptcha-authz-hpa
  labels:
    app: recaptcha-authz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recaptcha-authz
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recaptcha-authz-pdb
  labels:
    app: recaptcha-authz
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: recaptcha-authz

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: recaptcha-authz-vpa
  labels:
    app: recaptcha-authz
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: recaptcha-authz
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 1Gi
      controlledValues: RequestsAndLimits 